Repository Nuri-Capstone/frontend, pull requests merged in 2024-12, with the labels that each got.

#18 [refactor] 🔨 연령별 피드백 항목 제거
  app/mock-data/monthlyFeedbackData.js
  app/screens/home/Home.jsx
Labels: 🛠 fix, 💻 refactor

#20 [feat] 채팅방 GPT feedback 기능
  app/components/FeedbackContainer.jsx
  app/components/MessageContainer.jsx
  app/screens/chat/Chat.jsx
Labels: :kiwi_fruit: feature

#22 [feat] 채팅 종료 기능 추가
  app/screens/chat/Chat.jsx
Labels: :kiwi_fruit: feature

#26 [feat] 채팅방 리스트 프론트 기능 추가
  app/components/ConversationList.jsx
  app/screens/chatlist/ChatList.jsx
Labels: :kiwi_fruit: feature

#28 [feat] 채팅방 내용 불러오기 기능
  app/App.jsx
  app/assets/images/backButton.png
  app/screens/chat/ChatHistory.jsx
  app/screens/chatlist/ChatList.jsx
Labels: :kiwi_fruit: feature

#35 feat: ✨ 회원가입, 로그인, 인가 기능 추가
  app/assets/images/background.jpg
  app/assets/images/default-profile.png
  app/screens/auth/Login.jsx
  app/screens/auth/SignUp.jsx
  app/screens/chat/Chat.jsx
  app/screens/splash/Splash.jsx
  package-lock.json
  package.json
Labels: :kiwi_fruit: feature

#39 [feat] 채팅방 조회 API 연결
  app/components/ConversationList.jsx
  app/components/MessageContainer.jsx
  app/screens/chat/Chat.jsx
  app/screens/chat/ChatHistory.jsx
  app/screens/chatlist/ChatList.jsx
Labels: :kiwi_fruit: feature

#40 [fix] 채팅 종료 후 새 채팅 생성 수정
  app/screens/chat/Chat.jsx
  app/screens/chatlist/ChatList.jsx
Labels: 🛠 fix, :kiwi_fruit: feature

#42 [FEAT] ✨홈피드 프론트 통합
  app/screens/home/Home.jsx
Labels: :kiwi_fruit: feature
